"""empty message

Revision ID: 6bfd0acfe93c
Revises: 8da994562a1d
Create Date: 2026-03-22 11:59:54.947806

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6bfd0acfe93c'
down_revision = '8da994562a1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
