"""add_number_to_user

Revision ID: 8da994562a1d
Revises: ec97b67b0ff8
Create Date: 2026-03-22 11:53:02.744039

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8da994562a1d'
down_revision = 'ec97b67b0ff8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sa.String(length=50), nullable=True))
    
    # Backfill existing users with a unique number based on username
    op.execute("UPDATE \"user\" SET number = username || '-' || id::text WHERE number IS NULL")
    
    # Make the column NOT NULL after backfill
    op.alter_column('user', 'number', existing_type=sa.String(length=50), nullable=False)
    op.create_unique_constraint(None, 'user', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
