"""Initial migration

Revision ID: af594c22731c
Revises: 
Create Date: 2026-03-22 09:17:32.784698

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'af594c22731c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('pj', 'pf')", name='ck_client_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj', name='uq_client_cpf_cnpj')
    )
    op.create_table('service',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('is_expense', sa.Boolean(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pjpf', sa.String(length=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('pix', 'cash', 'card', 'transfer')", name='ck_transaction_payment_method'),
    sa.CheckConstraint("pjpf IN ('pj', 'pf')", name='ck_transaction_pjpf'),
    sa.CheckConstraint("status IN ('pending', 'paid', 'cancelled')", name='ck_transaction_status'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('service')
    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###
