"""auth

Revision ID: ec97b67b0ff8
Revises: af594c22731c
Create Date: 2026-03-22 11:28:39.345102

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ec97b67b0ff8'
down_revision = 'af594c22731c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('category', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.add_column('client', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_client_cpf_cnpj'), 'client', type_='unique')
    op.create_unique_constraint('uq_client_user_cpf_cnpj', 'client', ['user_id', 'cpf_cnpj'])
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.add_column('service', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'service', 'user', ['user_id'], ['id'])
    op.add_column('transaction', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'user_id')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint('uq_client_user_cpf_cnpj', 'client', type_='unique')
    op.create_unique_constraint(op.f('uq_client_cpf_cnpj'), 'client', ['cpf_cnpj'], postgresql_nulls_not_distinct=False)
    op.drop_column('client', 'user_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
